//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RayONS.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Lesson
    {
        public int LessonId { get; set; }
        public int SubcategoryId { get; set; }
        public string LessonName { get; set; }
        public System.Guid UserId { get; set; }
        public byte IsApproved { get; set; }
        public string Code { get; set; }
    
        public virtual Subcategory Subcategory { get; set; }
        public virtual User User { get; set; }
    }
}
