//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RayONS.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Test
    {
        public Test()
        {
            this.Questions = new HashSet<Question>();
            this.TestsResults = new HashSet<TestsResult>();
        }
    
        public int TestId { get; set; }
        public string TestName { get; set; }
        public System.Guid UserId { get; set; }
        public byte isApproved { get; set; }
        public Nullable<int> SubcategoryId { get; set; }
    
        public virtual ICollection<Question> Questions { get; set; }
        public virtual User User { get; set; }
        public virtual Subcategory Subcategory { get; set; }
        public virtual ICollection<TestsResult> TestsResults { get; set; }
    }
}
