//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RayONS.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class TestsResult
    {
        public int ResultId { get; set; }
        public int TestId { get; set; }
        public System.Guid UserId { get; set; }
        public int Result { get; set; }
        public int QuestionsCount { get; set; }
    
        public virtual Test Test { get; set; }
        public virtual User User { get; set; }
    }
}
